### ISSUE TITLE
Cannot log in from UK

### ISSUE THREAD

**Issue by wocsnia** [jpasqua/VisibleTesla#99]
Currently I cannot log in from the UK, with my new (v6.0) Tesla Model S 60, using either 0.28.\* or 0.29.0.

I have confirmed that I am using the same login details that I use with the Tesla android/iphone apps and with the teslamotors.com website.

I simply get the following error:

<pre>
Dec 23, 2014 12:28:46 AM org.noroomattheinn.visibletesla.VTUtils logAppInfo
INFO: VisibleTesla: 0.29.00
Dec 23, 2014 12:28:46 AM org.noroomattheinn.visibletesla.VTUtils logAppInfo
INFO: Max memory: 1760mb
Dec 23, 2014 12:28:46 AM org.noroomattheinn.visibletesla.VTUtils logAppInfo
INFO: JVM Arguments
Dec 23, 2014 12:28:46 AM org.noroomattheinn.visibletesla.CommandIssuer run
WARNING: Failed command (org.noroomattheinn.visibletesla.LoginController$AttemptLogin@78b9e139): 
Dec 23, 2014 12:28:59 AM org.noroomattheinn.tesla.Tesla login
SEVERE: null
java.io.IOException: Error while reading from POST: [500] Internal Server Error
<!DOCTYPE html>
<html>
<head>
  <title>We're sorry, but something went wrong (500)</title>
  <style type="text/css">
    body { background-color: #fff; color: #666; text-align: center; font-family: arial, sans-serif; }
    div.dialog {
      width: 25em;
      padding: 0 4em;
      margin: 4em auto 0 auto;
      border: 1px solid #ccc;
      border-right-color: #999;
      border-bottom-color: #999;
    }
    h1 { font-size: 100%; color: #f00; line-height: 1.5em; }
  </style>
</head>

<body>
  
  <div class="dialog">
    <h1>We're sorry, but something went wrong.</h1>
    <p>We've been notified about this issue and we'll take a look at it shortly.</p>
  </div>
</body>
</html>

    at us.monoid.web.AbstractResource.fill(AbstractResource.java:51)
    at us.monoid.web.Resty.fillResourceFromURL(Resty.java:432)
    at us.monoid.web.Resty.doPOSTOrPUT(Resty.java:394)
    at us.monoid.web.Resty.text(Resty.java:258)
    at us.monoid.web.Resty.text(Resty.java:284)
    at org.noroomattheinn.utils.RestyWrapper.text(RestyWrapper.java:107)
    at org.noroomattheinn.tesla.Tesla.login(Tesla.java:148)
    at org.noroomattheinn.tesla.Tesla.connect(Tesla.java:191)
    at org.noroomattheinn.visibletesla.LoginController$AttemptLogin.call(LoginController.java:201)
    at org.noroomattheinn.visibletesla.LoginController$AttemptLogin.call(LoginController.java:187)
    at org.noroomattheinn.visibletesla.CommandIssuer.run(CommandIssuer.java:74)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: https://portal.vn.teslamotors.com/login
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
    at us.monoid.web.AbstractResource.fill(AbstractResource.java:30)
    ... 11 more

Dec 23, 2014 12:28:59 AM org.noroomattheinn.visibletesla.CommandIssuer run
WARNING: Failed command (org.noroomattheinn.visibletesla.LoginController$AttemptLogin@2e29036b): 
</pre>

I have, unfortunately, been unable to get the latest git extract to work (Unfortunately, I am not familiar with ant and packaging java from git clones).

Any help appreciated - app looks awesome!

**Comment by jpasqua** [comment]
This is addressed in versions beyond 0.30.00, but they are "developer only" releases as described in the thread listed above.

**Comment by geirgp** [comment]
"developer only" as in "you have to build from source manually" ?

**Comment by jpasqua** [comment]
Yes, as in you need to build it yourself. I am making a prebuilt version for limited testing to see whether other people will be throttled. The answer is yes. Using this new version of VT with any regularity (which is the whole point) will cause you to be throttled at some point and will impact the operation of your mobile app as well.
